import { describe, it, expect } from 'vitest'
import { generateGerberOutput } from './gerberExporter'
import type { FootprintProject, ElementState } from '../types/pcb'

// ---------------------------------------------------------------------------
// Minimal project factory
// ---------------------------------------------------------------------------

function makeProject(elements: ElementState[]): FootprintProject {
  return {
    projectId: 'test',
    lastModified: 0,
    metadata: { name: 'Test', author: 'test' },
    gridSize: 2.54,
    elements: Object.fromEntries(elements.map((e) => [e.id, e])),
    nets: {},
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function lines(s: string): string[] {
  return s.split('\n')
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('generateGerberOutput', () => {
  it('emits Gerber header for copper1 layer', () => {
    const project = makeProject([])
    const { copper1 } = generateGerberOutput(project)
    const ls = lines(copper1)
    expect(ls[0]).toBe('G04 Generated by mob-gerb*')
    expect(ls[1]).toBe('G04 Layer: copper1*')
    expect(ls[2]).toBe('%FSLAX35Y35*%')
    expect(ls[3]).toBe('%MOMM*%')
    expect(ls[4]).toBe('%LPD*%')
    expect(ls.at(-1)).toBe('M02*')
  })

  it('encodes a circle pad as D03 flash with correct aperture diameter', () => {
    const pad: ElementState = {
      id: 'p1',
      type: 'circle',
      role: 'connector',
      pcbLayer: 'copper1',
      geom: { x: 1.27, y: 2.54, r: 0.4 },
      connector: { kind: 'smd', pin: 1, connectorId: 'c1', svgId: 's1' },
    }
    const { copper1 } = generateGerberOutput(makeProject([pad]))
    const ls = lines(copper1)
    // Aperture definition: diameter = 0.4 * 2 = 0.8
    expect(ls.some((l) => l === '%ADD10C,0.80000*%')).toBe(true)
    // Flash: x=1.27 → 127000, y=2.54 → 254000
    expect(ls.some((l) => l === 'X127000Y254000D03*')).toBe(true)
  })

  it('encodes a rect pad as D03 flash with correct aperture size', () => {
    const pad: ElementState = {
      id: 'r1',
      type: 'rect',
      role: 'connector',
      pcbLayer: 'copper0',
      geom: { x: 0, y: 0, w: 1.6, h: 0.8 },
      connector: { kind: 'smd', pin: 1, connectorId: 'c1', svgId: 's1' },
    }
    const { copper0 } = generateGerberOutput(makeProject([pad]))
    const ls = lines(copper0)
    expect(ls.some((l) => l === '%ADD10R,1.60000X0.80000*%')).toBe(true)
    expect(ls.some((l) => l === 'X0Y0D03*')).toBe(true)
  })

  it('encodes a polyline trace as D01 draw sequence', () => {
    const trace: ElementState = {
      id: 't1',
      type: 'polyline',
      role: 'copper-surface',
      pcbLayer: 'copper1',
      geom: {
        x: 0,
        y: 0,
        strokeWidth: 0.25,
        points: [
          { x: 0, y: 0 },
          { x: 5.08, y: 0 },
          { x: 5.08, y: 2.54 },
        ],
      },
    }
    const { copper1 } = generateGerberOutput(makeProject([trace]))
    const ls = lines(copper1)
    // Aperture for trace width 0.25
    expect(ls.some((l) => l === '%ADD10C,0.25000*%')).toBe(true)
    // Move to start
    expect(ls.some((l) => l === 'X0Y0D02*')).toBe(true)
    // Draw to second point: 5.08 → 508000
    expect(ls.some((l) => l === 'X508000Y0D01*')).toBe(true)
    // Draw to third point: 5.08, 2.54 → 508000, 254000
    expect(ls.some((l) => l === 'X508000Y254000D01*')).toBe(true)
  })

  it('assigns through-hole pad to drill file', () => {
    const pad: ElementState = {
      id: 'th1',
      type: 'circle',
      role: 'connector',
      pcbLayer: 'copper1',
      geom: { x: 2.54, y: 5.08, r: 0.5 },
      connector: { kind: 'through-hole', pin: 1, connectorId: 'c1', svgId: 's1' },
    }
    const { drill } = generateGerberOutput(makeProject([pad]))
    const ls = lines(drill)
    expect(ls[0]).toBe('M48')
    // Tool diameter = 0.5 * 2 = 1.0
    expect(ls.some((l) => l === 'T1C1.00000')).toBe(true)
    // Drill at x=2.54 → 254000, y=5.08 → 508000
    expect(ls.some((l) => l === 'X254000Y508000')).toBe(true)
    expect(ls.some((l) => l === 'M30')).toBe(true)
  })

  it('places SMD pad on copper but not in drill file', () => {
    const pad: ElementState = {
      id: 'smd1',
      type: 'circle',
      role: 'connector',
      pcbLayer: 'copper1',
      geom: { x: 1, y: 1, r: 0.4 },
      connector: { kind: 'smd', pin: 1, connectorId: 'c1', svgId: 's1' },
    }
    const { drill } = generateGerberOutput(makeProject([pad]))
    const ls = lines(drill)
    // No tool definitions when no through-hole pads
    expect(ls.some((l) => /^T\d+C/.test(l))).toBe(false)
  })

  it('assigns unique aperture codes to different pad sizes', () => {
    const pads: ElementState[] = [
      {
        id: 'p1',
        type: 'circle',
        role: 'connector',
        pcbLayer: 'copper1',
        geom: { x: 0, y: 0, r: 0.4 },
        connector: { kind: 'smd', pin: 1, connectorId: 'c1', svgId: 's1' },
      },
      {
        id: 'p2',
        type: 'circle',
        role: 'connector',
        pcbLayer: 'copper1',
        geom: { x: 2.54, y: 0, r: 0.6 },
        connector: { kind: 'smd', pin: 2, connectorId: 'c2', svgId: 's2' },
      },
    ]
    const { copper1 } = generateGerberOutput(makeProject(pads))
    const ls = lines(copper1)
    expect(ls.some((l) => l === '%ADD10C,0.80000*%')).toBe(true)
    expect(ls.some((l) => l === '%ADD11C,1.20000*%')).toBe(true)
  })

  it('routes silkscreen elements to silkscreen layer only', () => {
    const sk: ElementState = {
      id: 'sk1',
      type: 'polyline',
      role: 'silkscreen',
      pcbLayer: 'silkscreen',
      geom: {
        x: 0,
        y: 0,
        strokeWidth: 0.15,
        points: [
          { x: 0, y: 0 },
          { x: 3, y: 0 },
        ],
      },
    }
    const output = generateGerberOutput(makeProject([sk]))
    const silkLines = lines(output.silkscreen)
    const copperLines = lines(output.copper1)
    expect(silkLines.some((l) => l.endsWith('D01*'))).toBe(true)
    expect(copperLines.some((l) => l.endsWith('D01*'))).toBe(false)
  })

  it('empty project produces valid Gerber files with only header and footer', () => {
    const { copper1, copper0, drill } = generateGerberOutput(makeProject([]))
    expect(copper1).toContain('M02*')
    expect(copper0).toContain('M02*')
    expect(drill).toContain('M30')
  })
})
