/**
 * Gerber RS-274X and Excellon drill file generator.
 *
 * Coordinate system: all inputs are in millimetres.
 * Format statement: %FSLAX35Y35*% → 3 integer digits + 5 decimal digits.
 * Coordinate integer = Math.round(mm * 100_000).
 */

import type { ElementState, FootprintProject } from '../types/pcb'

// ---------------------------------------------------------------------------
// Coordinate encoding
// ---------------------------------------------------------------------------

const SCALE = 100_000 // 5 decimal places for mm mode

function coord(mm: number): string {
  return Math.round(mm * SCALE).toString()
}

// ---------------------------------------------------------------------------
// Aperture registry
// ---------------------------------------------------------------------------

type ApertureShape = 'C' | 'R'

interface ApertureDef {
  code: number
  shape: ApertureShape
  params: string // e.g. "0.80000" or "1.20000X0.80000"
}

class ApertureRegistry {
  private readonly map = new Map<string, ApertureDef>()
  private nextCode = 10

  private key(shape: ApertureShape, params: string): string {
    return `${shape}:${params}`
  }

  getOrCreate(shape: ApertureShape, params: string): ApertureDef {
    const k = this.key(shape, params)
    let def = this.map.get(k)
    if (!def) {
      def = { code: this.nextCode++, shape, params }
      this.map.set(k, def)
    }
    return def
  }

  definitions(): string[] {
    return Array.from(this.map.values()).map(
      (d) => `%ADD${d.code}${d.shape},${d.params}*%`,
    )
  }
}

// ---------------------------------------------------------------------------
// Gerber file builder
// ---------------------------------------------------------------------------

function gerberHeader(layerName: string): string[] {
  return [
    'G04 Generated by mob-gerb*',
    `G04 Layer: ${layerName}*`,
    '%FSLAX35Y35*%',
    '%MOMM*%',
    '%LPD*%',
  ]
}

type DrawOp =
  | { op: 'aperture'; dcode: number }
  | { op: 'move'; x: number; y: number }
  | { op: 'draw'; x: number; y: number }
  | { op: 'flash'; x: number; y: number }

function renderOps(ops: DrawOp[]): string[] {
  const lines: string[] = []
  let currentDcode = -1
  for (const op of ops) {
    switch (op.op) {
      case 'aperture':
        if (op.dcode !== currentDcode) {
          lines.push(`D${op.dcode}*`)
          currentDcode = op.dcode
        }
        break
      case 'move':
        lines.push(`X${coord(op.x)}Y${coord(op.y)}D02*`)
        break
      case 'draw':
        lines.push(`X${coord(op.x)}Y${coord(op.y)}D01*`)
        break
      case 'flash':
        lines.push(`X${coord(op.x)}Y${coord(op.y)}D03*`)
        break
    }
  }
  return lines
}

function buildGerberLayer(
  elements: ElementState[],
  layerName: string,
): string {
  const registry = new ApertureRegistry()
  const ops: DrawOp[] = []

  for (const el of elements) {
    const { geom } = el

    if (el.type === 'circle' && geom.r !== undefined) {
      const diameter = geom.r * 2
      const ap = registry.getOrCreate('C', diameter.toFixed(5))
      ops.push({ op: 'aperture', dcode: ap.code })
      ops.push({ op: 'flash', x: geom.x, y: geom.y })
    } else if (el.type === 'rect' && geom.w !== undefined && geom.h !== undefined) {
      const ap = registry.getOrCreate('R', `${geom.w.toFixed(5)}X${geom.h.toFixed(5)}`)
      ops.push({ op: 'aperture', dcode: ap.code })
      ops.push({ op: 'flash', x: geom.x, y: geom.y })
    } else if (
      (el.type === 'polyline' || el.type === 'line') &&
      geom.points &&
      geom.points.length >= 2 &&
      geom.strokeWidth !== undefined &&
      geom.strokeWidth > 0
    ) {
      const ap = registry.getOrCreate('C', geom.strokeWidth.toFixed(5))
      ops.push({ op: 'aperture', dcode: ap.code })
      const [first, ...rest] = geom.points
      ops.push({ op: 'move', x: first.x, y: first.y })
      for (const pt of rest) {
        ops.push({ op: 'draw', x: pt.x, y: pt.y })
      }
    }
    // polygon: not yet implemented — silently skipped per AC4
  }

  const apertureLines = registry.definitions()
  const dataLines = renderOps(ops)

  return [
    ...gerberHeader(layerName),
    ...apertureLines,
    ...dataLines,
    'M02*',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// Excellon drill file
// ---------------------------------------------------------------------------

interface DrillHole {
  x: number
  y: number
  diameter: number
}

class DrillToolRegistry {
  private readonly map = new Map<string, number>()
  private nextTool = 1

  getOrCreate(diameter: number): number {
    const k = diameter.toFixed(5)
    let t = this.map.get(k)
    if (!t) {
      t = this.nextTool++
      this.map.set(k, t)
    }
    return t
  }

  toolDefs(): Array<{ tool: number; diameter: number }> {
    return Array.from(this.map.entries()).map(([k, t]) => ({
      tool: t,
      diameter: parseFloat(k),
    }))
  }
}

function buildExcellonDrill(holes: DrillHole[]): string {
  const registry = new DrillToolRegistry()

  // Pre-register tools in hole order for determinism
  for (const h of holes) {
    registry.getOrCreate(h.diameter)
  }

  const header = [
    'M48',
    '; Generated by mob-gerb',
    'METRIC,TZ',
    'FMAT,2',
  ]

  const toolDefs = registry.toolDefs().map(
    ({ tool, diameter }) => `T${tool}C${diameter.toFixed(5)}`,
  )

  const body: string[] = ['%']
  let currentTool = -1
  for (const h of holes) {
    const t = registry.getOrCreate(h.diameter)
    if (t !== currentTool) {
      body.push(`T${t}`)
      currentTool = t
    }
    // Excellon: X/Y in mm with no decimal point (METRIC,TZ implicit precision)
    body.push(`X${coord(h.x)}Y${coord(h.y)}`)
  }
  body.push('M30')

  return [...header, ...toolDefs, ...body].join('\n')
}

// ---------------------------------------------------------------------------
// Layer partition
// ---------------------------------------------------------------------------

export type GerberOutput = {
  copper1: string  // .GTL — copper top
  copper0: string  // .GBL — copper bottom
  copper2?: string // .G1 — copper inner 1
  copper3?: string // .G2 — copper inner 2
  silkscreen: string  // .GTO — silkscreen top
  drill: string  // .DRL — Excellon drill
}

export function generateGerberOutput(project: FootprintProject): GerberOutput {
  const all = Object.values(project.elements)

  const copper1Els = all.filter((e) => e.pcbLayer === 'copper1')
  const copper0Els = all.filter((e) => e.pcbLayer === 'copper0')
  const copper2Els = all.filter((e) => e.pcbLayer === 'copper2')
  const copper3Els = all.filter((e) => e.pcbLayer === 'copper3')
  const silkscreenEls = all.filter((e) => e.pcbLayer === 'silkscreen')

  // Through-hole drill: circle connectors with kind === 'through-hole' on copper1
  const drillHoles: DrillHole[] = copper1Els
    .filter(
      (e) =>
        e.type === 'circle' &&
        e.role === 'connector' &&
        e.connector?.kind === 'through-hole' &&
        e.geom.r !== undefined,
    )
    .map((e) => ({ x: e.geom.x, y: e.geom.y, diameter: e.geom.r! * 2 }))

  return {
    copper1: buildGerberLayer(copper1Els, 'copper1'),
    copper0: buildGerberLayer(copper0Els, 'copper0'),
    copper2: buildGerberLayer(copper2Els, 'copper2'),
    copper3: buildGerberLayer(copper3Els, 'copper3'),
    silkscreen: buildGerberLayer(silkscreenEls, 'silkscreen'),
    drill: buildExcellonDrill(drillHoles),
  }
}
